"""Added a new Column pet

Revision ID: 1a64f1311b6c
Revises: ecb869d7ae85
Create Date: 2024-05-15 12:31:10.317497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a64f1311b6c'
down_revision = 'ecb869d7ae85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet', sa.String(), nullable=True))

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('pet')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('pet')

    # ### end Alembic commands ###
